name: Build and deploy .NET Core application to Web App api-geo-dev
on:
  push:
    branches:
    - main
env:
  WEBAPP_API_PACKAGE_PATH: ./Backend/WorkManagement.Api/publish/
  FRONTEND_PACKAGE_PATH: ./Frontend/build/
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: Backend/WorkManagement.Api
  FRONTEND_WORKING_DIRECTORY: Frontend
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}
    - name: Build React app
      run: npm run build
      working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: ${{ env.FRONTEND_PACKAGE_PATH }}
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: frontend
        path: ${{ env.FRONTEND_PACKAGE_PATH }}
    - name: Deploy to SmartAsp frontend
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: win1123.site4now.net
        username: shahnaupul-ui
        password: shahnaupul-ui
        local-dir: ${{ env.FRONTEND_PACKAGE_PATH }}
        exclude: |
          **/web.config*
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v5
      with:
          name: frontend  
  build-backend:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} -r win-x86 --self-contained true  --output "${{ env.WEBAPP_API_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.WEBAPP_API_PACKAGE_PATH }}
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.WEBAPP_API_PACKAGE_PATH }}
    - name: Deploy to SmartAsp backend
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: win1123.site4now.net
        username: shahnaupul-api
        password: shahnaupul-api
        local-dir: ${{ env.WEBAPP_API_PACKAGE_PATH }}
        exclude: |
          **/web.config*
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v5
      with:
          name: webapp  
